#!/usr/bin/env php
<?php
declare(strict_types=1);

use Symfony\Component\Dotenv\Dotenv;
use Weph\ObsidianTools\Actions\Action;
use Weph\ObsidianTools\Actions\GenerateBookmarks;
use Weph\ObsidianTools\Actions\GenerateJournalSummaries;
use Weph\ObsidianTools\Actions\GenerateReadingList;
use Weph\ObsidianTools\Actions\GenerateWeeklySummary;
use Weph\ObsidianTools\Actions\SwimReport\GenerateSwimReports;
use Weph\ObsidianTools\Actions\UpdateBreadcrumbs;
use Weph\ObsidianTools\Vault\VaultUsingFilesystem;

require_once __DIR__ . '/vendor/autoload.php';

(new Dotenv())->load(__DIR__ . '/.env', __DIR__ . '/.env.local');

error_reporting(E_ALL ^ E_DEPRECATED);

$vault = VaultUsingFilesystem::atPath($_ENV['VAULT_PATH']);

/** @var list<Action> $actions */
$actions = [
    new GenerateSwimReports($vault),
    new GenerateJournalSummaries($vault),
    new GenerateWeeklySummary($vault),
    new UpdateBreadcrumbs($vault),
    new GenerateReadingList($vault),
    new GenerateBookmarks($vault)
];

foreach ($actions as $action) {
    printf("Running %s...", get_class($action));

    $action->run();

    printf("done\n");
}
