#!/usr/bin/env php
<?php
declare(strict_types=1);

use Symfony\Component\Dotenv\Dotenv;
use Weph\ObsidianTools\DailyNotes\JournalSummary\JournalSummaryGenerator;
use Weph\ObsidianTools\DailyNotes\SwimReport\SwimReportGenerator;
use Weph\ObsidianTools\DailyNotes\UpdateBreadcrumbs;
use Weph\ObsidianTools\ReadingListGenerator;
use Weph\ObsidianTools\Vault\VaultUsingFilesystem;

require_once __DIR__ . '/vendor/autoload.php';

(new Dotenv())->load(__DIR__ . '/.env', __DIR__ . '/.env.local');

error_reporting(E_ALL ^ E_DEPRECATED);

$vault = VaultUsingFilesystem::atPath($_ENV['VAULT_PATH']);

printf("Generating swim reports...\n");
(new SwimReportGenerator($vault))->run();
printf("Done\n\n");

printf("Generating journal summaries...\n");
(new JournalSummaryGenerator($vault))->run();
printf("Done\n\n");

printf("Updating breadcrumbs...\n");
(new UpdateBreadcrumbs($vault))->run();
printf("Done\n\n");

printf("Generate reading list...\n");
(new ReadingListGenerator($vault))->run();
printf("Done\n\n");
